

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "uv pip install --system '.[dev]' && 
             uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"

