name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"   # e.g. v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make install-dev

      - name: Test with pytest
        run: |
          make test

      - name: Build documentation
        run: |
          mkdocs build

      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force

      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')  # only when a version tag is pushed
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
